# Generated by Django 3.1 on 2021-01-05 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0002_auto_20201212_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Clip title')),
                ('description', models.TextField()),
                ('views_count', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='channels.channel', verbose_name='Parent channel')),
            ],
        ),
    ]
