# Generated by Django 3.1 on 2020-12-12 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0002_auto_20201212_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=128, verbose_name='Clip title')),
                ('description', models.TextField()),
                ('views_count', models.PositiveIntegerField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='channels.channel', verbose_name='Parent channel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
